### ISSUE TITLE
TODO: Unit Testing

### ISSUE THREAD

**Issue by mikeccuk2005** [digithun/react-native-builder#3]
- [ ] FCM setup Unit Test
- [ ] FBSDK setup Unit Test
- [ ] Nap setup Unit Test
